# Site settings
title: willingsealğŸ˜…
SEOTitle: willingsealâ¤ï¸
header-img: img/setup_home_top_bg_1.jpg
email: willingseal@gmail.com
description: "ï½ï½åˆé€‚çš„æ‰æ˜¯é€‚åˆçš„ï½ï½."
keyword: "äº§å“è®¾è®¡, UIè®¾è®¡, willingsealçš„åšå®¢, willingseal, iOS, Apple, iPhone"
url: "https://willingseal.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/willingseal/willingseal.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "äº§å“å°â¤ï¸â¤ï¸åœ¨è†¨èƒ€ï½."
sidebar-avatar: /img/setup_home_top_bg.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     willingseal
# zhihu_username:     qiubaiying
github_username:    willingseal
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
twitter_username:   willingseal



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
disqus_username: willing_seal

# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: f2c84e7629bb1446c1a4                            #ç”Ÿæˆçš„clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #ç”Ÿæˆçš„clientSecret
  repo: willingseal.github.io    #ä»“åº“åç§°
  owner: willingseal    #githubç”¨æˆ·å
  admin: willingseal
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 1              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "willingseal",
        href: "https://willingseal.github.io/"
    },{
        title: "behance",
        href: "https://www.behance.net/"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
